name: Develop Pipeline TESTE

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'cat package.json antes'
        run: cat ./package.json

      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'frontend-'
          INPUT_TAG-PREFIX: 'teste-'
        env:
          PACKAGEJSON_DIR: 'frontend'
          tag-prefix: 'tazxs'
          INPUT_TAG-PREFIX: 'aaaa'

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'cat package.json frontend'
        run: cat ./frontend/package.json
