name: Master Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_BFF: ${{ secrets.BFF_URL }}

    steps:
      - uses: actions/checkout@v2

      - name: Dependências centrais
        uses: bahmutov/npm-install@v1

      - name: Dependências Frontend
        uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend

      - name: Lint
        run: yarn lint

      - name: Atualizar versão do projeto
        uses: phips28/gh-action-bump-version@master

      - name: Ler a versão do projeto
        id: packageVersion
        uses: martinbeentjes/npm-get-version-action@master

      - name: build Front
        run: cd frontend && CI=false yarn build
        env:
          REACT_APP_VERSION: ${{ steps.packageVersion.outputs.current-version}}

      - uses: actions/upload-artifact@v2
        with:
          name: build-front
          path: frontend/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_SSH: ${{ secrets.SERVER_SSH }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-front
          path: frontend/build

      - name: Deploy Frontend
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH }}
          SOURCE: 'frontend/build/'
          ARGS: '-rltgoDzvO --delete'
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: '/home/samu_gcloud/samu-radio-tracker/frontend/build/'

      - name: Deploy Backend
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH }}
          SOURCE: 'backend/*'
          ARGS: '-rltgoDzvO --delete'
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: '/home/samu_gcloud/samu-radio-tracker/backend/'
